<link rel="stylesheet" href="<?php echo site_url('assets2/css/bootstrap.min.css') ?>">
<link rel="stylesheet" href="<?php echo site_url('assets2/css/owl.carousel.min.css') ?>">
<link rel="stylesheet" href="<?php echo site_url('assets2/css/flaticon.css') ?>">
<link rel="stylesheet" href="<?php echo site_url('assets2/css/slicknav.css') ?>">
<link rel="stylesheet" href="<?php echo site_url('assets2/css/animate.min.css') ?>">
<link rel="stylesheet" href="<?php echo site_url('assets2/css/magnific-popup.css') ?>">
<link rel="stylesheet" href="<?php echo site_url('assets2/css/fontawesome-all.min.css') ?>">
<link rel="stylesheet" href="<?php echo site_url('assets2/css/themify-icons.css') ?>">
<link rel="stylesheet" href="<?php echo site_url('assets2/css/slick.css') ?>">
<link rel="stylesheet" href="<?php echo site_url('assets2/css/nice-select.css') ?>">
<link rel="stylesheet" href="<?php echo site_url('assets2/css/style.css') ?>">